jobs:
  include:
  - language: node_js
    node_js:
      - "stable"
    cache:
      directories:
        - node_modules
    script:
      - cd UI
      - npm install
      - npm run build    
  - language: csharp
    dist: bionic
    mono: none
    dotnet: 3.1
    script:
      - cd API
      - dotnet build